# Generated by Django 4.2.6 on 2024-08-31 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0002_expensedatamodel_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensedatamodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
