# Generated by Django 4.2.6 on 2024-09-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0003_rename_user_id_expensedatamodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedatamodel',
            name='expense_amount',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
