# Generated by Django 4.2.6 on 2024-09-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0005_alter_expensedatamodel_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedatamodel',
            name='expense_date',
            field=models.CharField(max_length=50),
        ),
    ]
