# Generated by Django 4.2.6 on 2024-09-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0006_alter_expensedatamodel_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedatamodel',
            name='expense_date',
            field=models.DateField(max_length=50),
        ),
    ]
