# Generated by Django 4.2.6 on 2024-02-02 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0002_product_orders_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='customer_name',
            new_name='username',
        ),
    ]
