# Generated by Django 4.2.6 on 2024-03-07 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0003_rename_customer_name_customers_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
