# Generated by Django 4.2.6 on 2024-04-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodel',
            old_name='e_mail',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='l_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='f_name',
            new_name='last_name',
        ),
    ]
