# Generated by Django 4.2.6 on 2024-04-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_library_app', '0002_rename_e_mail_registermodel_email_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('pages', models.IntegerField()),
                ('pdf', models.FileField(upload_to='uploads/')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
