# Generated by Django 4.2.6 on 2024-05-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_library_app', '0003_addbookmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbookmodel',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
