# Generated by Django 4.2.6 on 2024-05-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_library_app', '0004_alter_addbookmodel_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbookmodel',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Fiction', 'Fiction'), ('Science', 'Science')], max_length=100),
        ),
    ]
