# Generated by Django 4.2.6 on 2024-05-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_library_app', '0005_alter_addbookmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbookmodel',
            name='contributed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
